import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Image from 'next/image'; // Import Image component from Next.js
import Head from 'next/head'; // Import Head component from Next.js

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "STUDY BUDDY",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
            <Head>
                {/* Google tag (gtag.js) */}
                <script async src="https://www.googletagmanager.com/gtag/js?id=G-Q5QB8JDFPK"></script>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            window.dataLayer = window.dataLayer || [];
                            function gtag(){dataLayer.push(arguments);}
                            gtag('js', new Date());
                            gtag('config', 'G-Q5QB8JDFPK');
                        `,
                    }}
                />
            </Head>
            <body className={`${inter.className}`}>
            <header className="app-header">
                <div className="logo-container">
                    <Image
                        src="/creativity.png" // Path to the logo file in the public folder
                        alt="Study Buddy Flashcards Logo"
                        width={50} // Adjust width as needed
                        height={50} // Adjust height as needed
                    />
                </div>
            </header>
            <main>
                {children}
            </main>
            </body>
            </html>
        </ClerkProvider>
    );
}
